# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biofeedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.TextField(max_length=200, verbose_name='name')),
                ('antecedentes', models.TextField(max_length=200)),
                ('examen_mental', models.TextField(max_length=200, verbose_name='name')),
                ('analisi', models.TextField(max_length=200, verbose_name='name')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='name')),
                ('apellido', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
                ('carrera', models.CharField(choices=[('00', 'Biología'), ('01', 'Física'), ('02', 'Licenciatura en Matemáticas Matemáticas'), ('03', 'Química'), ('04', 'Derecho'), ('05', 'Economía'), ('06', 'Filosofía'), ('07', 'Historia y Archivística'), ('08', 'Licenciatura en Educación Básica con Énfasis en Ciencias Naturales y Educación Ambiental'), ('09', 'Licenciatura en Educación Básica con Énfasis en Lengua Castellana'), ('10', 'Licenciatura en Español y Literatura'), ('11', 'Licenciatura en Inglés'), ('12', 'Licenciatura en Lenguas Extranjeras con énfasis en Inglés'), ('13', 'Licenciatura en Literatura y Lengua Castellana'), ('14', 'Licenciatura en Música'), ('15', 'Trabajo Social'), ('16', 'Diseño Industrial'), ('17', 'Ingeniería Civil'), ('18', 'Ingeniería de Eléctrica'), ('19', 'Ingeniería de Electrónica'), ('20', 'Ingeniería Industrial'), ('21', 'Ingeniería Mecánica'), ('22', 'Ingeniería de Sistemas'), ('23', 'Geología'), ('24', 'Ingeniería Metalúrgica'), ('25', 'Ingeniería de Petróleos'), ('26', 'Ingeniería Química'), ('27', 'Microbiología y Bioanálisis'), ('28', 'Enfermería'), ('29', 'Fisioterapia'), ('30', 'Medicina'), ('31', 'Nutrición y Dietética'), ('32', 'Ingeniería Forestal'), ('33', 'Zootecnia'), ('34', 'Turismo')], default=30, max_length=2)),
                ('telefono', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=250)),
                ('edad', models.CharField(max_length=200)),
                ('cree_dios', models.BooleanField(default=True)),
                ('religion', models.CharField(choices=[(0, 'Catolico'), (1, 'Evangelico'), (2, 'Adventista')], default=0, max_length=1)),
                ('trabaja', models.BooleanField(default=False)),
                ('lateralidad', models.CharField(choices=[(0, 'Diestro'), (1, 'Ciniestro'), (2, 'Ambidiestro')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biofeedback.Paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='historiamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biofeedback.Paciente'),
        ),
    ]
